jdbcUrl: jdbc:mysql://114.215.28.111:28743/laimi?useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&useSSL=false
username: laimi_read
password: 7GSdadjf7s9x
autoCommit: false
maximumPoolSize: 50
minimumIdle: 10
connectionTestQuery: SELECT 1
dataSource:
  cachePrepStmts: true
  cacheResultSetMetadata: true
  cacheServerConfiguration: true
  elideSetAutoCommits: true
  maintainTimeStats: false
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  rewriteBatchedStatements: true
  useLocalSessionState: true
  useServerPrepStmts: true